Zookeeper 更新到新版本按刷新出错问题
Problem accessing /. Reason:

Failed to execute action module
Caused by:

com.alibaba.citrus.service.pipeline.PipelineException: Failed to execute action module